POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "MikM",
    "password": "Salainen",
    "name": "Tuomas Testaaja"
}


// TuoT, Salasana, Tuomas Testaaja
// MikM, Salainen, Mikko Mallikas
